execution:
  max_trades_per_day: 10
  mode: live
logging:
  enabled: true
postgres:
  database: tradingbot
  host: localhost
  password: ${POSTGRES_PASSWORD}
  port: 5432
  user: postgres
trading:
  futures: true
  futures_symbols:
  - ETHUSDT
  - ADAUSDT
  - SOLUSDT
  - BNBUSDT
  - SUIUSDT
  - XRPUSDT
  - ENAUSDT
  - 1000PEPEUSDT
  stake_percent: 0.02
  symbols:
  - ETH/USDT
  - ADA/USDT
  - SOL/USDT
  - BNB/USDT
  - SUI/USDT
  - XRP/USDT
  - ENA/USDT
  - MDT/USDT
  - PEPE/USDT
  timeframe: 1m
