execution:
  max_trades_per_day: 10
  mode: live
logging:
  enabled: true
postgres:
  database: tradingbot
  host: localhost
  password: ${POSTGRES_PASSWORD}
  port: 5432
  user: postgres
trading:
  futures: false
  timeframe: 1m
