binance:
  api_key: ${BINANCE_API_KEY_TEST}
  api_secret: ${BINANCE_API_SECRET_TEST}
trading:
  symbols:
  - BTC/USDT
  - ETH/USDT
  - BNB/USDT
  timeframe: 1m
  stake_percent: 0.02
  futures: false
execution:
  mode: live
  max_trades_per_day: 3
logging:
  enabled: true
  path: logs/trades.csv
telegram:
  token: ${TELEGRAM_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}
