binance:
  api_key: ${BINANCE_API_KEY}
  api_secret: ${BINANCE_API_SECRET}
execution:
  max_trades_per_day: 10
  mode: live
logging:
  enabled: true
  path: logs/trades.csv
telegram:
  chat_id: ${TELEGRAM_CHAT_ID}
  token: ${TELEGRAM_TOKEN}
trading:
  futures: true
  futures_symbols:
  - ETHUSDT
  - ADAUSDT
  - SOLUSDT
  - BNBUSDT
  - BTCUSDT
  - SUIUSDT
  - XRPUSDT
  stake_percent: 0.02
  symbols:
  - ETH/USDT
  - ADA/USDT
  - SOL/USDT
  - BNB/USDT
  - BTC/USDT
  - SUI/USDT
  - XRP/USDT
  timeframe: 5m
