binance:
  api_key: ${BINANCE_API_KEY}
  api_secret: ${BINANCE_API_SECRET}
trading:
  symbols:
  - BTC/USDT
  - ETH/USDT
  - BNB/USDT
  - SOL/USDT
  - PEPE/USDT
  - SUI/USDT
  timeframe: 5m
  stake_percent: 0.02
  futures: false
execution:
  mode: live
  max_trades_per_day: 10
logging:
  enabled: true
  path: logs/trades.csv
telegram:
  token: ${TELEGRAM_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}
